import {
  cilApplicationsSettings,
  cilFeaturedPlaylist,
  cilMenu,
  cilPuzzle,
  cilSpeedometer,
  cilUser,
  cilNoteAdd,
  cilPeople,
  cilBarcode,
  cilChart,
  cilNewspaper,
  cilSpreadsheet,
  cilAirplay,
  cilBurger,
  cilCarAlt,
  cilSearch,
  cilCalendarCheck,
  cilTask,
  cilTerminal,
  cilGarage,
  cilBusAlt,
  cilScreenDesktop,
  cilDevices,
  cilMonitor,
  cilLaptop,
  cilRestaurant,
  cilPizza,
  cilUserFollow,
  cilUserUnfollow,
  cilGroup,
  cilUserPlus,
  cilWc,
  cilCalendar,
  cilBriefcase,
  cilBank,
  cilWarning

} from '@coreui/icons';

export const iconSubset = {
  cilApplicationsSettings,
  cilMenu,
  cilSpeedometer,
  cilPuzzle,
  cilFeaturedPlaylist,
  cilUser,
  cilNoteAdd,
  cilPeople,
  cilBarcode,
  cilChart,
  cilNewspaper,
  cilSpreadsheet,
  cilAirplay,
  cilBurger,
  cilCarAlt,
  cilSearch,
  cilCalendarCheck,
  cilTask,
  cilTerminal,
  cilGarage,
  cilBusAlt,
  cilScreenDesktop,
  cilDevices,
  cilMonitor,
  cilLaptop,
  cilRestaurant,
  cilPizza,
  cilUserFollow,
  cilUserUnfollow,
  cilGroup,
  cilUserPlus,
  cilWc,
  cilCalendar,
  cilBriefcase,
  cilBank,
  cilWarning,


};

export enum IconSubset {
  cilApplicationsSettings = 'cilApplicationsSettings',
  cilMenu = 'cilMenu',
  cilSpeedometer = 'cilSpeedometer',
  cilPuzzle = 'cilPuzzle',
  cilFeaturedPlaylist ='cilFeaturedPlaylist',
  cilUser='cilUser',
  cilNoteAdd = 'cilNoteAdd',
  cilPeople = 'cilPeople',
  cilBarcode = '  cilBarcode',
  cilChart = '  cilChart',
  cilNewspaper = '  cilNewspaper',
  cilSpreadsheet= 'cilSpreadsheet',
  cilairplay = 'cilAirplay',
  cilBurger = 'cilBurger',
  cilCarAlt = 'cilCarAlt',
  cilSearch = '  cilSearch',
  cilCalendarCheck = 'cilCalendarCheck',
  cilTask = '  cilTask,',
  cilTerminal = '  cilTerminal',
  cilGarage = 'cilGarage',
  cilBusAlt = '  cilBusAlt',
  cilScreenDesktop ='cilScreenDesktop',
  cilDevices = 'cilDevices',
  cilMonitor = ' cilMonitor',
  cilLaptop = ' cilLaptop',
  cilRestaurant = 'cilRestaurant',
  cilPizza = 'cilPizza',
  cilUserFollow = '  cilUserFollow',
  cilUserUnfollow = 'cilUserUnfollow',
  cilGroup = 'cilGroup',
  cilWc = ' cilWc',
  cilCalendar = 'cilCalendar',
  cilBriefcase = 'cilBriefcase',
  cilBank =  ' cilBank',
  cilWarning = 'cilWarning',
}
